### ISSUE TITLE
sed_breadcrumbs correction

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#57]
$urlpaths = ($home) ? array_merge(array("/" => $L['Home']), $urlpaths) : $urlpaths;
change
$urlpaths = ($home) ? array_merge(array("#" => $L['Home']), $urlpaths) : $urlpaths;

**Comment by avego** [comment]
On a basic web page, the # symbol is used to link to a section within a page. So that the browser jumps down to that section after the page loads.
/ - root link!

Example: 
1) On domain **https://seditio.org** - link / leads to **https://seditio.org/**
2) **http://localhost/seditio** - link / leads to **https://localhost/**

So everything is right here!
$urlpaths = ($home) ? array_merge(array("/" => $L['Home']), $urlpaths) : $urlpaths;

**Comment by SeditioCMS** [comment]
It doesn't work either, I'll post a video soon.

**Comment by avego** [comment]
I fix this problem. Thanks Kaan!
