### ISSUE TITLE
how can i get plugin subcategory title

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#62]
how can i get plugin subcategory title
$plug_title and $plug_subtitle

url: plug/test
sub url: plug/test?catid=1 and subtitle

i couldn't explain it fully but how can i get title and category title in plugin

**Comment by avego** [comment]
If we are talking about the meta descritption and the title tag ($out['subtitle'], $out['subdesc']), then in the plugin, to change these variables, you need to write a part of the plugin with the header.first hook. There is no other way to do it, because the body of the standalone plugin in plug.inc.php is connected after header.php
